// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Software_Taller_y_Repuestos.Models;

#nullable disable

namespace Software_Taller_y_Repuestos.Migrations
{
    [DbContext(typeof(TallerRepuestosDbContext))]
    [Migration("20241005050753_Contrasenna")]
    partial class Contrasenna
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductosModelo", b =>
                {
                    b.Property<int>("ProductoId")
                        .HasColumnType("int")
                        .HasColumnName("ProductoID");

                    b.Property<int>("ModeloId")
                        .HasColumnType("int")
                        .HasColumnName("ModeloID");

                    b.HasKey("ProductoId", "ModeloId")
                        .HasName("PK__Producto__1B96ABA86357B125");

                    b.HasIndex("ModeloId");

                    b.ToTable("ProductosModelos", (string)null);
                });

            modelBuilder.Entity("ProveedoresProducto", b =>
                {
                    b.Property<int>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("ProveedorId", "ProductoId")
                        .HasName("PK__Proveedo__4B6560B3A9D5AFBE");

                    b.HasIndex("ProductoId");

                    b.ToTable("ProveedoresProductos", (string)null);
                });

            modelBuilder.Entity("Software_Taller_y_Repuestos.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoriaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoriaId")
                        .HasName("PK__Categori__F353C1C57A85E13B");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Software_Taller_y_Repuestos.Models.CodigosDescuento", b =>
                {
                    b.Property<int>("CodigoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CodigoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoId"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("FechaExpiracion")
                        .HasColumnType("datetime");

                    b.Property<string>("TipoDescuento")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("ValorDescuento")
                        .HasColumnType("decimal(12, 2)");

                    b.HasKey("CodigoId")
                        .HasName("PK__CodigosD__DB319CF3407E9E87");

                    b.ToTable("CodigosDescuento", (string)null);
                });

            modelBuilder.Entity("Software_Taller_y_Repuestos.Models.CuentaBancarium", b =>
                {
                    b.Property<int>("CuentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CuentaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CuentaId"));

                    b.Property<string>("Banco")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroCuenta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TipoCuenta")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    b.HasKey("CuentaId")
                        .HasName("PK__CuentaBa__40072EA196982E58");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CuentaBancaria");
                });

            modelBuilder.Entity("Software_Taller_y_Repuestos.Models.DetallesFactura", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DetalleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("FacturaId")
                        .HasColumnType("int")
                        .HasColumnName("FacturaID");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int")
                        .HasColumnName("ProductoID");

                    b.HasKey("DetalleId")
                        .HasName("PK__Detalles__6E19D6FA0DD8E7EA");

                    b.HasIndex("FacturaId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DetallesFactura", (string)null);
                });

            modelBuilder.Entity("Software_Taller_y_Repuestos.Models.Factura", b =>
                {
                    b.Property<int>("FacturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FacturaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacturaId"));

                    b.Property<int?>("CodigoDescuentoId")
                        .HasColumnType("int")
                        .HasColumnName("CodigoDescuentoID");

                    b.Property<bool>("CorreoEnviado")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Descuento")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("Impuestos")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    b.HasKey("FacturaId")
                        .HasName("PK__Facturas__5C02480534443468");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("Software_Taller_y_Repuestos.Models.Horario", b =>
                {
                    b.Property<int>("HorarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HorarioID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HorarioId"));

                    b.Property<decimal>("Ausencias")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<decimal>("HorasExtras")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("HorasTrabajadas")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("Permisos")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    b.HasKey("HorarioId")
                        .HasName("PK__Horarios__BB881A9E0A46E376");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Horarios");
                });

            modelBuilder.Entity("Software_Taller_y_Repuestos.Models.ModelosAuto", b =>
                {
                    b.Property<int>("ModeloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ModeloID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModeloId"));

                    b.Property<int>("Año")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ModeloId")
                        .HasName("PK__ModelosA__FA6052BA4C821877");

                    b.ToTable("ModelosAutos");
                });

            modelBuilder.Entity("Software_Taller_y_Repuestos.Models.PagosEmpleado", b =>
                {
                    b.Property<int>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PagoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PagoId"));

                    b.Property<decimal?>("Bonificaciones")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<decimal?>("Deducciones")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<DateTime>("FechaPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("HorasExtras")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("SalarioPagado")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    b.HasKey("PagoId")
                        .HasName("PK__PagosEmp__F00B6158767EE0C1");

                    b.HasIndex("UsuarioId");

                    b.ToTable("PagosEmpleados");
                });

            modelBuilder.Entity("Software_Taller_y_Repuestos.Models.Producto", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProductoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int")
                        .HasColumnName("CategoriaID");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Imagen")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Marca")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrecioCompra")
                        .HasColumnType("decimal(12, 4)");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(12, 4)");

                    b.HasKey("ProductoId")
                        .HasName("PK__Producto__A430AE8382118DC5");

                    b.HasIndex("CategoriaId");

                    b.HasIndex(new[] { "Codigo" }, "UQ__Producto__06370DAC3327131C")
                        .IsUnique();

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Software_Taller_y_Repuestos.Models.Proveedore", b =>
                {
                    b.Property<int>("ProveedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProveedorId"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ruc")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("RUC");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ProveedorId")
                        .HasName("PK__Proveedo__61266A59B2C75164");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("Software_Taller_y_Repuestos.Models.Role", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RolID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RolId")
                        .HasName("PK__Roles__F92302D1DDE5C884");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RolId = 1,
                            NombreRol = "Admin"
                        },
                        new
                        {
                            RolId = 2,
                            NombreRol = "Cliente"
                        },
                        new
                        {
                            RolId = 3,
                            NombreRol = "Empleado"
                        });
                });

            modelBuilder.Entity("Software_Taller_y_Repuestos.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Contrasenna")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("FechaIngreso")
                        .HasColumnType("datetime");

                    b.Property<string>("Imagen")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("RolID");

                    b.Property<decimal?>("SalarioBase")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UsuarioId")
                        .HasName("PK__Usuarios__2B3DE798CBEB8A18");

                    b.HasIndex("RolId");

                    b.HasIndex(new[] { "Correo" }, "UQ__Usuarios__60695A19AF60258D")
                        .IsUnique()
                        .HasFilter("[Correo] IS NOT NULL");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ProductosModelo", b =>
                {
                    b.HasOne("Software_Taller_y_Repuestos.Models.ModelosAuto", null)
                        .WithMany()
                        .HasForeignKey("ModeloId")
                        .IsRequired()
                        .HasConstraintName("FK__Productos__Model__403A8C7D");

                    b.HasOne("Software_Taller_y_Repuestos.Models.Producto", null)
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .IsRequired()
                        .HasConstraintName("FK__Productos__Produ__3F466844");
                });

            modelBuilder.Entity("ProveedoresProducto", b =>
                {
                    b.HasOne("Software_Taller_y_Repuestos.Models.Producto", null)
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .IsRequired()
                        .HasConstraintName("FK__Proveedor__Produ__6477ECF3");

                    b.HasOne("Software_Taller_y_Repuestos.Models.Proveedore", null)
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .IsRequired()
                        .HasConstraintName("FK__Proveedor__Prove__6383C8BA");
                });

            modelBuilder.Entity("Software_Taller_y_Repuestos.Models.CuentaBancarium", b =>
                {
                    b.HasOne("Software_Taller_y_Repuestos.Models.Usuario", "Usuario")
                        .WithMany("CuentaBancaria")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK__CuentaBan__Usuar__5BE2A6F2");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Software_Taller_y_Repuestos.Models.DetallesFactura", b =>
                {
                    b.HasOne("Software_Taller_y_Repuestos.Models.Factura", "Factura")
                        .WithMany("DetallesFacturas")
                        .HasForeignKey("FacturaId")
                        .IsRequired()
                        .HasConstraintName("FK__DetallesF__Factu__4D94879B");

                    b.HasOne("Software_Taller_y_Repuestos.Models.Producto", "Producto")
                        .WithMany("DetallesFacturas")
                        .HasForeignKey("ProductoId")
                        .IsRequired()
                        .HasConstraintName("FK__DetallesF__Produ__4E88ABD4");

                    b.Navigation("Factura");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Software_Taller_y_Repuestos.Models.Factura", b =>
                {
                    b.HasOne("Software_Taller_y_Repuestos.Models.Usuario", "Usuario")
                        .WithMany("Facturas")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK__Facturas__Usuari__4AB81AF0");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Software_Taller_y_Repuestos.Models.Horario", b =>
                {
                    b.HasOne("Software_Taller_y_Repuestos.Models.Usuario", "Usuario")
                        .WithMany("Horarios")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK__Horarios__Usuari__5812160E");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Software_Taller_y_Repuestos.Models.PagosEmpleado", b =>
                {
                    b.HasOne("Software_Taller_y_Repuestos.Models.Usuario", "Usuario")
                        .WithMany("PagosEmpleados")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK__PagosEmpl__Usuar__52593CB8");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Software_Taller_y_Repuestos.Models.Producto", b =>
                {
                    b.HasOne("Software_Taller_y_Repuestos.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .IsRequired()
                        .HasConstraintName("FK__Productos__Categ__3A81B327");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Software_Taller_y_Repuestos.Models.Usuario", b =>
                {
                    b.HasOne("Software_Taller_y_Repuestos.Models.Role", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .IsRequired()
                        .HasConstraintName("FK__Usuarios__RolID__45F365D3");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Software_Taller_y_Repuestos.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Software_Taller_y_Repuestos.Models.Factura", b =>
                {
                    b.Navigation("DetallesFacturas");
                });

            modelBuilder.Entity("Software_Taller_y_Repuestos.Models.Producto", b =>
                {
                    b.Navigation("DetallesFacturas");
                });

            modelBuilder.Entity("Software_Taller_y_Repuestos.Models.Role", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Software_Taller_y_Repuestos.Models.Usuario", b =>
                {
                    b.Navigation("CuentaBancaria");

                    b.Navigation("Facturas");

                    b.Navigation("Horarios");

                    b.Navigation("PagosEmpleados");
                });
#pragma warning restore 612, 618
        }
    }
}
